services:
  migrate:
    build:
      context: .
    command: ["/migrate", "-database", "sqlite3:///tmp/data/db.sqlite", "-path", "/migrations", "up"]
    volumes:
      - .data:/tmp/data
      - ./migrations:/migrations
    restart: "no"

  calculator:
    build:
      context: .
    command: ["/calculator"]
    ports:
      - "8080:8080"
      - "8081:8081"
      - "50051:50051"
    environment:
      LOG_LEVEL: "info"
      MGMT_ADDR: ":8081"
      GRPC_ADDR: ":50051"
      HTTP_ADDR: ":8080"
      DB_SQLITE_PATH: "/tmp/data/db.sqlite"
      AUTH_JWT_SECRET: "jwt-secret"
      AUTH_JWT_EXPIRATION_TIME: "1h"
      TIME_ADDITION_MS: "1000"
      TIME_SUBTRACTION_MS: "1000"
      TIME_MULTIPLICATIONS_MS: "1000"
      TIME_DIVISIONS_MS: "1000"
    restart: unless-stopped
    volumes:
      - .data:/tmp/data
    depends_on:
      migrate:
        condition: service_completed_successfully

  agent:
    build:
      context: .
    command: ["/agent"]
    environment:
      LOG_LEVEL: "info"
      MGMT_ADDR: ":8082"
      CALCULATOR_API_ADDR: "calculator:50051"
      COMPUTING_POWER: "4"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - calculator
