// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	auth "edu-final-calculate-api/internal/calculator/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function with given fields: _a0
func (_m *MockAuth) GenerateJWT(_a0 auth.UserInfo) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.UserInfo) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(auth.UserInfo) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(auth.UserInfo) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuth_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type MockAuth_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - _a0 auth.UserInfo
func (_e *MockAuth_Expecter) GenerateJWT(_a0 interface{}) *MockAuth_GenerateJWT_Call {
	return &MockAuth_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", _a0)}
}

func (_c *MockAuth_GenerateJWT_Call) Run(run func(_a0 auth.UserInfo)) *MockAuth_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.UserInfo))
	})
	return _c
}

func (_c *MockAuth_GenerateJWT_Call) Return(_a0 string, _a1 error) *MockAuth_GenerateJWT_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuth_GenerateJWT_Call) RunAndReturn(run func(auth.UserInfo) (string, error)) *MockAuth_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
